"""se crea la migracion para agregar features a la tabla plan

Revision ID: 14a2116f4cf8
Revises: 5823429fc3fe
Create Date: 2025-09-26 18:53:23.876930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14a2116f4cf8'
down_revision = '5823429fc3fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('features', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_column('features')

    # ### end Alembic commands ###
