"""se agrega user a customer v2

Revision ID: 5823429fc3fe
Revises: ab7295ac63a6
Create Date: 2025-09-24 02:00:05.178316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5823429fc3fe'
down_revision = 'ab7295ac63a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('customers_user_id_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('customers_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('customers_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.create_unique_constraint(batch_op.f('customers_user_id_key'), ['user_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
